//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_APC_SS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Webservice_APC_SS", ConfigurationName="WS_APC_SS.Webservice_APC_SS")]
    public interface Webservice_APC_SS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Webservice_APC_SS/Alta_SS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WS_APC_SS.Alta_SSResponse1> Alta_SSAsync(WS_APC_SS.Alta_SSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Webservice_APC_SS/GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WS_APC_SS.GetVersionResponse1> GetVersionAsync(WS_APC_SS.GetVersionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Webservice_APC_SS")]
    public partial class Alta_SS
    {
        
        private T_Alta_SS_InputRequest alta_SSRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public T_Alta_SS_InputRequest Alta_SSRequest
        {
            get
            {
                return this.alta_SSRequestField;
            }
            set
            {
                this.alta_SSRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservice_APC_SS")]
    public partial class T_Alta_SS_InputRequest
    {
        
        private string sucursalPresentacionField;
        
        private string fabricanteField;
        
        private string tipoPersonaField;
        
        private decimal montoSolicitadoField;
        
        private bool montoSolicitadoFieldSpecified;
        
        private string telefonoField;
        
        private string prioridadField;
        
        private string motivoField;
        
        private string correoElectronicoField;
        
        private string razonSocialField;
        
        private string observacionesField;
        
        private string fechaField;
        
        private decimal montoAcordadoField;
        
        private bool montoAcordadoFieldSpecified;
        
        private string fechaFinCargaSolicitudField;
        
        private string tipoDocField;
        
        private string tipoConsultaField;
        
        private string sexoField;
        
        private string origenField;
        
        private string codigoValidacionField;
        
        private string tipoCuitField;
        
        private string nroDocField;
        
        private string fechaDeCargaField;
        
        private string estadoField;
        
        private string bancaField;
        
        private string nroCuitField;
        
        private System.DateTime fechaNacimientoPFField;
        
        private bool fechaNacimientoPFFieldSpecified;
        
        private decimal montoRealDolaresField;
        
        private bool montoRealDolaresFieldSpecified;
        
        private string exposicionField;
        
        private string testFlagField;
        
        private decimal montoRealField;
        
        private bool montoRealFieldSpecified;
        
        private decimal montoAproximadoField;
        
        private bool montoAproximadoFieldSpecified;
        
        private string sucursalClienteField;
        
        private string subproductoField;
        
        private string productoField;
        
        private string resultadoBureauField;
        
        private string productoaComprarField;
        
        private string nroOperacionField;
        
        private string apellidoField;
        
        private string sucursalCertificadoField;
        
        private string nombreField;
        
        private System.DateTime fechaConstitucionField;
        
        private bool fechaConstitucionFieldSpecified;
        
        private string canalWSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sucursalPresentacion
        {
            get
            {
                return this.sucursalPresentacionField;
            }
            set
            {
                this.sucursalPresentacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fabricante
        {
            get
            {
                return this.fabricanteField;
            }
            set
            {
                this.fabricanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tipoPersona
        {
            get
            {
                return this.tipoPersonaField;
            }
            set
            {
                this.tipoPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal montoSolicitado
        {
            get
            {
                return this.montoSolicitadoField;
            }
            set
            {
                this.montoSolicitadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoSolicitadoSpecified
        {
            get
            {
                return this.montoSolicitadoFieldSpecified;
            }
            set
            {
                this.montoSolicitadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string prioridad
        {
            get
            {
                return this.prioridadField;
            }
            set
            {
                this.prioridadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string correoElectronico
        {
            get
            {
                return this.correoElectronicoField;
            }
            set
            {
                this.correoElectronicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string razonSocial
        {
            get
            {
                return this.razonSocialField;
            }
            set
            {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string observaciones
        {
            get
            {
                return this.observacionesField;
            }
            set
            {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal montoAcordado
        {
            get
            {
                return this.montoAcordadoField;
            }
            set
            {
                this.montoAcordadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoAcordadoSpecified
        {
            get
            {
                return this.montoAcordadoFieldSpecified;
            }
            set
            {
                this.montoAcordadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string fechaFinCargaSolicitud
        {
            get
            {
                return this.fechaFinCargaSolicitudField;
            }
            set
            {
                this.fechaFinCargaSolicitudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string tipoDoc
        {
            get
            {
                return this.tipoDocField;
            }
            set
            {
                this.tipoDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string tipoConsulta
        {
            get
            {
                return this.tipoConsultaField;
            }
            set
            {
                this.tipoConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string sexo
        {
            get
            {
                return this.sexoField;
            }
            set
            {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string origen
        {
            get
            {
                return this.origenField;
            }
            set
            {
                this.origenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string codigoValidacion
        {
            get
            {
                return this.codigoValidacionField;
            }
            set
            {
                this.codigoValidacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string tipoCuit
        {
            get
            {
                return this.tipoCuitField;
            }
            set
            {
                this.tipoCuitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string nroDoc
        {
            get
            {
                return this.nroDocField;
            }
            set
            {
                this.nroDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string fechaDeCarga
        {
            get
            {
                return this.fechaDeCargaField;
            }
            set
            {
                this.fechaDeCargaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string banca
        {
            get
            {
                return this.bancaField;
            }
            set
            {
                this.bancaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string nroCuit
        {
            get
            {
                return this.nroCuitField;
            }
            set
            {
                this.nroCuitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=24)]
        public System.DateTime fechaNacimientoPF
        {
            get
            {
                return this.fechaNacimientoPFField;
            }
            set
            {
                this.fechaNacimientoPFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoPFSpecified
        {
            get
            {
                return this.fechaNacimientoPFFieldSpecified;
            }
            set
            {
                this.fechaNacimientoPFFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public decimal montoRealDolares
        {
            get
            {
                return this.montoRealDolaresField;
            }
            set
            {
                this.montoRealDolaresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoRealDolaresSpecified
        {
            get
            {
                return this.montoRealDolaresFieldSpecified;
            }
            set
            {
                this.montoRealDolaresFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string exposicion
        {
            get
            {
                return this.exposicionField;
            }
            set
            {
                this.exposicionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string testFlag
        {
            get
            {
                return this.testFlagField;
            }
            set
            {
                this.testFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public decimal montoReal
        {
            get
            {
                return this.montoRealField;
            }
            set
            {
                this.montoRealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoRealSpecified
        {
            get
            {
                return this.montoRealFieldSpecified;
            }
            set
            {
                this.montoRealFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public decimal montoAproximado
        {
            get
            {
                return this.montoAproximadoField;
            }
            set
            {
                this.montoAproximadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoAproximadoSpecified
        {
            get
            {
                return this.montoAproximadoFieldSpecified;
            }
            set
            {
                this.montoAproximadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string sucursalCliente
        {
            get
            {
                return this.sucursalClienteField;
            }
            set
            {
                this.sucursalClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string subproducto
        {
            get
            {
                return this.subproductoField;
            }
            set
            {
                this.subproductoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string producto
        {
            get
            {
                return this.productoField;
            }
            set
            {
                this.productoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string resultadoBureau
        {
            get
            {
                return this.resultadoBureauField;
            }
            set
            {
                this.resultadoBureauField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string productoaComprar
        {
            get
            {
                return this.productoaComprarField;
            }
            set
            {
                this.productoaComprarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string nroOperacion
        {
            get
            {
                return this.nroOperacionField;
            }
            set
            {
                this.nroOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string apellido
        {
            get
            {
                return this.apellidoField;
            }
            set
            {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string sucursalCertificado
        {
            get
            {
                return this.sucursalCertificadoField;
            }
            set
            {
                this.sucursalCertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=39)]
        public System.DateTime fechaConstitucion
        {
            get
            {
                return this.fechaConstitucionField;
            }
            set
            {
                this.fechaConstitucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaConstitucionSpecified
        {
            get
            {
                return this.fechaConstitucionFieldSpecified;
            }
            set
            {
                this.fechaConstitucionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string canalWS
        {
            get
            {
                return this.canalWSField;
            }
            set
            {
                this.canalWSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservice_APC_SS")]
    public partial class T_RptaVersion_SS
    {
        
        private T_RptaVersion_SSResultado resultadoField;
        
        private T_RptaVersion_SSVersion versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public T_RptaVersion_SSResultado Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public T_RptaVersion_SSVersion Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Webservice_APC_SS")]
    public partial class T_RptaVersion_SSResultado
    {
        
        private int codigoField;
        
        private string descripcionField;
        
        private bool mensajeAplicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool MensajeAplicacion
        {
            get
            {
                return this.mensajeAplicacionField;
            }
            set
            {
                this.mensajeAplicacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Webservice_APC_SS")]
    public partial class T_RptaVersion_SSVersion
    {
        
        private string numeroField;
        
        private string notasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Notas
        {
            get
            {
                return this.notasField;
            }
            set
            {
                this.notasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservice_APC_SS")]
    public partial class Solicitud
    {
        
        private string usuarioField;
        
        private int sucursalField;
        
        private string aplicacionField;
        
        private bool reenvioField;
        
        private bool reenvioFieldSpecified;
        
        private int journalLocalField;
        
        private bool journalLocalFieldSpecified;
        
        private int journalReversaField;
        
        private bool journalReversaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int Sucursal
        {
            get
            {
                return this.sucursalField;
            }
            set
            {
                this.sucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Aplicacion
        {
            get
            {
                return this.aplicacionField;
            }
            set
            {
                this.aplicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool Reenvio
        {
            get
            {
                return this.reenvioField;
            }
            set
            {
                this.reenvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReenvioSpecified
        {
            get
            {
                return this.reenvioFieldSpecified;
            }
            set
            {
                this.reenvioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int JournalLocal
        {
            get
            {
                return this.journalLocalField;
            }
            set
            {
                this.journalLocalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JournalLocalSpecified
        {
            get
            {
                return this.journalLocalFieldSpecified;
            }
            set
            {
                this.journalLocalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int JournalReversa
        {
            get
            {
                return this.journalReversaField;
            }
            set
            {
                this.journalReversaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JournalReversaSpecified
        {
            get
            {
                return this.journalReversaFieldSpecified;
            }
            set
            {
                this.journalReversaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Webservice_APC_SS")]
    public partial class T_Alta_SS_InputResponde
    {
        
        private string codigoField;
        
        private string descripcionField;
        
        private string nroSolicitudField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nroSolicitud
        {
            get
            {
                return this.nroSolicitudField;
            }
            set
            {
                this.nroSolicitudField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Webservice_APC_SS")]
    public partial class Alta_SSResponse
    {
        
        private T_Alta_SS_InputResponde alta_SSResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Alta_SSResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public T_Alta_SS_InputResponde Alta_SSResponse1
        {
            get
            {
                return this.alta_SSResponse1Field;
            }
            set
            {
                this.alta_SSResponse1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Alta_SSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice_APC_SS", Order=0)]
        public WS_APC_SS.Alta_SS Alta_SS;
        
        public Alta_SSRequest()
        {
        }
        
        public Alta_SSRequest(WS_APC_SS.Alta_SS Alta_SS)
        {
            this.Alta_SS = Alta_SS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Alta_SSResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice_APC_SS", Order=0)]
        public WS_APC_SS.Alta_SSResponse Alta_SSResponse;
        
        public Alta_SSResponse1()
        {
        }
        
        public Alta_SSResponse1(WS_APC_SS.Alta_SSResponse Alta_SSResponse)
        {
            this.Alta_SSResponse = Alta_SSResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Webservice_APC_SS")]
    public partial class GetVersion
    {
        
        private Solicitud solicitudVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Solicitud SolicitudVersion
        {
            get
            {
                return this.solicitudVersionField;
            }
            set
            {
                this.solicitudVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Webservice_APC_SS")]
    public partial class GetVersionResponse
    {
        
        private T_RptaVersion_SS versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public T_RptaVersion_SS Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice_APC_SS", Order=0)]
        public WS_APC_SS.GetVersion GetVersion;
        
        public GetVersionRequest()
        {
        }
        
        public GetVersionRequest(WS_APC_SS.GetVersion GetVersion)
        {
            this.GetVersion = GetVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Webservice_APC_SS", Order=0)]
        public WS_APC_SS.GetVersionResponse GetVersionResponse;
        
        public GetVersionResponse1()
        {
        }
        
        public GetVersionResponse1(WS_APC_SS.GetVersionResponse GetVersionResponse)
        {
            this.GetVersionResponse = GetVersionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface Webservice_APC_SSChannel : WS_APC_SS.Webservice_APC_SS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class Webservice_APC_SSClient : System.ServiceModel.ClientBase<WS_APC_SS.Webservice_APC_SS>, WS_APC_SS.Webservice_APC_SS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Webservice_APC_SSClient() : 
                base(Webservice_APC_SSClient.GetDefaultBinding(), Webservice_APC_SSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Webservice_APC_SSHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Webservice_APC_SSClient(EndpointConfiguration endpointConfiguration) : 
                base(Webservice_APC_SSClient.GetBindingForEndpoint(endpointConfiguration), Webservice_APC_SSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Webservice_APC_SSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Webservice_APC_SSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Webservice_APC_SSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Webservice_APC_SSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Webservice_APC_SSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_APC_SS.Alta_SSResponse1> WS_APC_SS.Webservice_APC_SS.Alta_SSAsync(WS_APC_SS.Alta_SSRequest request)
        {
            return base.Channel.Alta_SSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_APC_SS.Alta_SSResponse1> Alta_SSAsync(WS_APC_SS.Alta_SS Alta_SS)
        {
            WS_APC_SS.Alta_SSRequest inValue = new WS_APC_SS.Alta_SSRequest();
            inValue.Alta_SS = Alta_SS;
            return ((WS_APC_SS.Webservice_APC_SS)(this)).Alta_SSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_APC_SS.GetVersionResponse1> WS_APC_SS.Webservice_APC_SS.GetVersionAsync(WS_APC_SS.GetVersionRequest request)
        {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_APC_SS.GetVersionResponse1> GetVersionAsync(WS_APC_SS.GetVersion GetVersion)
        {
            WS_APC_SS.GetVersionRequest inValue = new WS_APC_SS.GetVersionRequest();
            inValue.GetVersion = GetVersion;
            return ((WS_APC_SS.Webservice_APC_SS)(this)).GetVersionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Webservice_APC_SSHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Webservice_APC_SSHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("https://intapp0000.dcc.dbna.net/Webservice_APC_SS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Webservice_APC_SSClient.GetBindingForEndpoint(EndpointConfiguration.Webservice_APC_SSHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Webservice_APC_SSClient.GetEndpointAddress(EndpointConfiguration.Webservice_APC_SSHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            Webservice_APC_SSHttpPort,
        }
    }
}
