//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_APC_SS_Consulta
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Weservice_APC_SS_Consulta", ConfigurationName="WS_APC_SS_Consulta.Weservice_APC_SS_Consulta")]
    public interface Weservice_APC_SS_Consulta
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Weservice_APC_SS_Consulta/Consulta_SS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WS_APC_SS_Consulta.Consulta_SSResponse1> Consulta_SSAsync(WS_APC_SS_Consulta.Consulta_SSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Weservice_APC_SS_Consulta/GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WS_APC_SS_Consulta.GetVersionResponse1> GetVersionAsync(WS_APC_SS_Consulta.GetVersionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Weservice_APC_SS_Consulta")]
    public partial class Consulta_SS
    {
        
        private T_Consulta_SS_Request consulta_SS_RequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public T_Consulta_SS_Request Consulta_SS_Request
        {
            get
            {
                return this.consulta_SS_RequestField;
            }
            set
            {
                this.consulta_SS_RequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Weservice_APC_SS_Consulta")]
    public partial class T_Consulta_SS_Request
    {
        
        private string nroSSField;
        
        private string cUITField;
        
        private string testFlagField;
        
        private string codIdentField;
        
        private string nroOperacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nroSS
        {
            get
            {
                return this.nroSSField;
            }
            set
            {
                this.nroSSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CUIT
        {
            get
            {
                return this.cUITField;
            }
            set
            {
                this.cUITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string testFlag
        {
            get
            {
                return this.testFlagField;
            }
            set
            {
                this.testFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codIdent
        {
            get
            {
                return this.codIdentField;
            }
            set
            {
                this.codIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nroOperacion
        {
            get
            {
                return this.nroOperacionField;
            }
            set
            {
                this.nroOperacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Weservice_APC_SS_Consulta")]
    public partial class T_Version
    {
        
        private T_VersionResultado resultadoField;
        
        private T_VersionVersion versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public T_VersionResultado Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public T_VersionVersion Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Weservice_APC_SS_Consulta")]
    public partial class T_VersionResultado
    {
        
        private int codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Weservice_APC_SS_Consulta")]
    public partial class T_VersionVersion
    {
        
        private string numeroField;
        
        private string notasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Notas
        {
            get
            {
                return this.notasField;
            }
            set
            {
                this.notasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Weservice_APC_SS_Consulta")]
    public partial class T_SolicitudVersion
    {
        
        private string usuarioField;
        
        private int sucursalField;
        
        private string aplicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int Sucursal
        {
            get
            {
                return this.sucursalField;
            }
            set
            {
                this.sucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Aplicacion
        {
            get
            {
                return this.aplicacionField;
            }
            set
            {
                this.aplicacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Weservice_APC_SS_Consulta")]
    public partial class T_Consulta_SS_Response
    {
        
        private string cUITField;
        
        private T_Consulta_SS_ResponseSolServicio[] solServicioField;
        
        private string codIdentField;
        
        private string codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CUIT
        {
            get
            {
                return this.cUITField;
            }
            set
            {
                this.cUITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("solServicio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public T_Consulta_SS_ResponseSolServicio[] solServicio
        {
            get
            {
                return this.solServicioField;
            }
            set
            {
                this.solServicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codIdent
        {
            get
            {
                return this.codIdentField;
            }
            set
            {
                this.codIdentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Weservice_APC_SS_Consulta")]
    public partial class T_Consulta_SS_ResponseSolServicio
    {
        
        private string numeroField;
        
        private string estadoField;
        
        private string origenField;
        
        private string motivoField;
        
        private string nroOperacionField;
        
        private string sucPresentacionField;
        
        private string productoField;
        
        private string subproductoField;
        
        private string bancaField;
        
        private string prioridadField;
        
        private string tipoConsultaField;
        
        private string resultadoBureauField;
        
        private string exposicionField;
        
        private string observacionesField;
        
        private string montoSolicitadoField;
        
        private string montoAcordadoField;
        
        private string fechaCreacionField;
        
        private string fechaAperturaField;
        
        private string fechaVencimientoField;
        
        private string fechaAprobacionField;
        
        private string fechaAcreditacionField;
        
        private string fechaCompensacionField;
        
        private string fabricanteField;
        
        private string productoComprarField;
        
        private string codValidacionField;
        
        private string telefonoField;
        
        private string correoElectronicoField;
        
        private string canalField;
        
        private string varAlfaNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numero
        {
            get
            {
                return this.numeroField;
            }
            set
            {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string origen
        {
            get
            {
                return this.origenField;
            }
            set
            {
                this.origenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nroOperacion
        {
            get
            {
                return this.nroOperacionField;
            }
            set
            {
                this.nroOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sucPresentacion
        {
            get
            {
                return this.sucPresentacionField;
            }
            set
            {
                this.sucPresentacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string producto
        {
            get
            {
                return this.productoField;
            }
            set
            {
                this.productoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string subproducto
        {
            get
            {
                return this.subproductoField;
            }
            set
            {
                this.subproductoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string banca
        {
            get
            {
                return this.bancaField;
            }
            set
            {
                this.bancaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string prioridad
        {
            get
            {
                return this.prioridadField;
            }
            set
            {
                this.prioridadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string tipoConsulta
        {
            get
            {
                return this.tipoConsultaField;
            }
            set
            {
                this.tipoConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string resultadoBureau
        {
            get
            {
                return this.resultadoBureauField;
            }
            set
            {
                this.resultadoBureauField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string exposicion
        {
            get
            {
                return this.exposicionField;
            }
            set
            {
                this.exposicionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string observaciones
        {
            get
            {
                return this.observacionesField;
            }
            set
            {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string montoSolicitado
        {
            get
            {
                return this.montoSolicitadoField;
            }
            set
            {
                this.montoSolicitadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string montoAcordado
        {
            get
            {
                return this.montoAcordadoField;
            }
            set
            {
                this.montoAcordadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string fechaCreacion
        {
            get
            {
                return this.fechaCreacionField;
            }
            set
            {
                this.fechaCreacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string fechaApertura
        {
            get
            {
                return this.fechaAperturaField;
            }
            set
            {
                this.fechaAperturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string fechaVencimiento
        {
            get
            {
                return this.fechaVencimientoField;
            }
            set
            {
                this.fechaVencimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string fechaAprobacion
        {
            get
            {
                return this.fechaAprobacionField;
            }
            set
            {
                this.fechaAprobacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string fechaAcreditacion
        {
            get
            {
                return this.fechaAcreditacionField;
            }
            set
            {
                this.fechaAcreditacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string fechaCompensacion
        {
            get
            {
                return this.fechaCompensacionField;
            }
            set
            {
                this.fechaCompensacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string fabricante
        {
            get
            {
                return this.fabricanteField;
            }
            set
            {
                this.fabricanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string productoComprar
        {
            get
            {
                return this.productoComprarField;
            }
            set
            {
                this.productoComprarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string codValidacion
        {
            get
            {
                return this.codValidacionField;
            }
            set
            {
                this.codValidacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string correoElectronico
        {
            get
            {
                return this.correoElectronicoField;
            }
            set
            {
                this.correoElectronicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string canal
        {
            get
            {
                return this.canalField;
            }
            set
            {
                this.canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string varAlfaNum
        {
            get
            {
                return this.varAlfaNumField;
            }
            set
            {
                this.varAlfaNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Weservice_APC_SS_Consulta")]
    public partial class Consulta_SSResponse
    {
        
        private T_Consulta_SS_Response consulta_SS_ResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public T_Consulta_SS_Response Consulta_SS_Response
        {
            get
            {
                return this.consulta_SS_ResponseField;
            }
            set
            {
                this.consulta_SS_ResponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_SSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Weservice_APC_SS_Consulta", Order=0)]
        public WS_APC_SS_Consulta.Consulta_SS Consulta_SS;
        
        public Consulta_SSRequest()
        {
        }
        
        public Consulta_SSRequest(WS_APC_SS_Consulta.Consulta_SS Consulta_SS)
        {
            this.Consulta_SS = Consulta_SS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_SSResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Weservice_APC_SS_Consulta", Order=0)]
        public WS_APC_SS_Consulta.Consulta_SSResponse Consulta_SSResponse;
        
        public Consulta_SSResponse1()
        {
        }
        
        public Consulta_SSResponse1(WS_APC_SS_Consulta.Consulta_SSResponse Consulta_SSResponse)
        {
            this.Consulta_SSResponse = Consulta_SSResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Weservice_APC_SS_Consulta")]
    public partial class GetVersion
    {
        
        private T_SolicitudVersion solicitudVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public T_SolicitudVersion SolicitudVersion
        {
            get
            {
                return this.solicitudVersionField;
            }
            set
            {
                this.solicitudVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Weservice_APC_SS_Consulta")]
    public partial class GetVersionResponse
    {
        
        private T_Version versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public T_Version Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Weservice_APC_SS_Consulta", Order=0)]
        public WS_APC_SS_Consulta.GetVersion GetVersion;
        
        public GetVersionRequest()
        {
        }
        
        public GetVersionRequest(WS_APC_SS_Consulta.GetVersion GetVersion)
        {
            this.GetVersion = GetVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Weservice_APC_SS_Consulta", Order=0)]
        public WS_APC_SS_Consulta.GetVersionResponse GetVersionResponse;
        
        public GetVersionResponse1()
        {
        }
        
        public GetVersionResponse1(WS_APC_SS_Consulta.GetVersionResponse GetVersionResponse)
        {
            this.GetVersionResponse = GetVersionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface Weservice_APC_SS_ConsultaChannel : WS_APC_SS_Consulta.Weservice_APC_SS_Consulta, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class Weservice_APC_SS_ConsultaClient : System.ServiceModel.ClientBase<WS_APC_SS_Consulta.Weservice_APC_SS_Consulta>, WS_APC_SS_Consulta.Weservice_APC_SS_Consulta
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Weservice_APC_SS_ConsultaClient() : 
                base(Weservice_APC_SS_ConsultaClient.GetDefaultBinding(), Weservice_APC_SS_ConsultaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Weservice_APC_SS_ConsultaHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Weservice_APC_SS_ConsultaClient(EndpointConfiguration endpointConfiguration) : 
                base(Weservice_APC_SS_ConsultaClient.GetBindingForEndpoint(endpointConfiguration), Weservice_APC_SS_ConsultaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Weservice_APC_SS_ConsultaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Weservice_APC_SS_ConsultaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Weservice_APC_SS_ConsultaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Weservice_APC_SS_ConsultaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Weservice_APC_SS_ConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_APC_SS_Consulta.Consulta_SSResponse1> WS_APC_SS_Consulta.Weservice_APC_SS_Consulta.Consulta_SSAsync(WS_APC_SS_Consulta.Consulta_SSRequest request)
        {
            return base.Channel.Consulta_SSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_APC_SS_Consulta.Consulta_SSResponse1> Consulta_SSAsync(WS_APC_SS_Consulta.Consulta_SS Consulta_SS)
        {
            WS_APC_SS_Consulta.Consulta_SSRequest inValue = new WS_APC_SS_Consulta.Consulta_SSRequest();
            inValue.Consulta_SS = Consulta_SS;
            return ((WS_APC_SS_Consulta.Weservice_APC_SS_Consulta)(this)).Consulta_SSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_APC_SS_Consulta.GetVersionResponse1> WS_APC_SS_Consulta.Weservice_APC_SS_Consulta.GetVersionAsync(WS_APC_SS_Consulta.GetVersionRequest request)
        {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_APC_SS_Consulta.GetVersionResponse1> GetVersionAsync(WS_APC_SS_Consulta.GetVersion GetVersion)
        {
            WS_APC_SS_Consulta.GetVersionRequest inValue = new WS_APC_SS_Consulta.GetVersionRequest();
            inValue.GetVersion = GetVersion;
            return ((WS_APC_SS_Consulta.Weservice_APC_SS_Consulta)(this)).GetVersionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Weservice_APC_SS_ConsultaHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Weservice_APC_SS_ConsultaHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("https://intapp0000.cc.bna.net/Weservice_APC_SS_Consulta");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Weservice_APC_SS_ConsultaClient.GetBindingForEndpoint(EndpointConfiguration.Weservice_APC_SS_ConsultaHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Weservice_APC_SS_ConsultaClient.GetEndpointAddress(EndpointConfiguration.Weservice_APC_SS_ConsultaHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            Weservice_APC_SS_ConsultaHttpPort,
        }
    }
}
